config/routes.rb
Rails.application.routes.draw do
  resources :journalists
  resources :settings
  resources :themes
  resources :categories
  resources :stories
  devise_for :users
  
  get '/', to: 'home#index'
  get '/about', to: 'home#about'
  get '/contact', to: 'home#contact'
  root to: "home#index"

  get '/journalistdashboard', to: 'home#dashboard'
  get '/drafts', to: 'stories#drafts'
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"


  #this has to be last so user created categories don't override the application links
  get '/:name', to: 'categories#public'

end

app/models/theme.rb
class Theme < ApplicationRecord
  has_one_attached :logo
end

app/controllers/themes_controller.rb
class ThemesController < ApplicationController
  before_action :set_theme, only: %i[ show edit update destroy ]
  before_action :authenticate_user!
  before_action :only_editors

  def only_editors
    unless current_user.journalist.is_editor?
      flash[:alert] = 'You are not signed in as an authorized editor of this newspaper.'
      redirect_back(fallback_location: root_path)
    end
  end

  # GET /themes or /themes.json
  def index
    @themes = Theme.all
  end

  # GET /themes/1 or /themes/1.json
  def show
  end

  # GET /themes/new
  def new
    @theme = Theme.new
  end

  # GET /themes/1/edit
  def edit
  end

  # POST /themes or /themes.json
  def create
    @theme = Theme.new(theme_params)

    respond_to do |format|
      if @theme.save
        format.html { redirect_to theme_url(@theme), notice: "Theme was successfully created." }
        format.json { render :show, status: :created, location: @theme }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @theme.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /themes/1 or /themes/1.json
  def update
    respond_to do |format|
      if @theme.update(theme_params)
        format.html { redirect_to theme_url(@theme), notice: "Theme was successfully updated." }
        format.json { render :show, status: :ok, location: @theme }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @theme.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /themes/1 or /themes/1.json
  def destroy
    @theme.destroy!

    respond_to do |format|
      format.html { redirect_to themes_url, notice: "Theme was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_theme
      @theme = Theme.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def theme_params
      params.require(:theme).permit(:name, :backgroundcolor, :headingcolor, :textcolor, :primarycolor, :secondarycolor, :tertiarycolor, :quaternarycolor, :logo, :maxwidth, :customcss, :customhead)
    end
end

app/helpers/themes_helper.rb
module ThemesHelper
end

app/views/themes/_form.html.erb
<%= form_with(model: theme) do |form| %>
  <% if theme.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(theme.errors.count, "error") %> prohibited this theme from being saved:</h2>

      <ul>
        <% theme.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :backgroundcolor, style: "display: block" %>
    <%= form.color_field :backgroundcolor %>
  </div>

  <div class="field">
    <%= form.label :headingcolor, style: "display: block" %>
    <%= form.color_field :headingcolor %>
  </div>

  <div class="field">
    <%= form.label :textcolor, style: "display: block" %>
    <%= form.color_field :textcolor %>
  </div>

  <div class="field">
    <%= form.label :primarycolor, style: "display: block" %>
    <%= form.color_field :primarycolor %>
  </div>

  <div class="field">
    <%= form.label :secondarycolor, style: "display: block" %>
    <%= form.color_field :secondarycolor %>
  </div>

  <div class="field">
    <%= form.label :tertiarycolor, style: "display: block" %>
    <%= form.color_field :tertiarycolor %>
  </div>

  <div class="field">
    <%= form.label :quaternarycolor, style: "display: block" %>
    <%= form.color_field :quaternarycolor %>
  </div>

  <div class="field">
    <%= form.label :logo, style: "display: block" %>
    <%= form.file_field :logo %>
  </div>

  <div class="field">
    <%= form.label :maxwidth, style: "display: block" %>
    <%= form.text_field :maxwidth %>
  </div>

  <div class="field">
    <%= form.label "Custom Header Content (For Fonts, Scripts, Charts, JS libraries, ETC)", style: "display: block" %>
    <%= form.text_area :customhead %>
  </div>

  <div class="field">
    <%= form.label :customcss, style: "display: block" %>
    <%= form.text_area :customcss %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/themes/_theme.html.erb
<div id="<%= dom_id theme %>">
  <!-- OLD
  <p>
    <strong>Name:</strong>
    <%= theme.name %>
  </p>

  <p>
    <strong>Backgroundcolor:</strong>
    <%= theme.backgroundcolor %>
  </p>

  <p>
    <strong>Headingcolor:</strong>
    <%= theme.headingcolor %>
  </p>

  <p>
    <strong>Textcolor:</strong>
    <%= theme.textcolor %>
  </p>

  <p>
    <strong>Primarycolor:</strong>
    <%= theme.primarycolor %>
  </p>

  <p>
    <strong>Secondarycolor:</strong>
    <%= theme.secondarycolor %>
  </p>

  <p>
    <strong>Tertiarycolor:</strong>
    <%= theme.tertiarycolor %>
  </p>

  <p>
    <strong>Quaternarycolor:</strong>
    <%= theme.quaternarycolor %>
  </p>

  <p>
    <strong>Logo:</strong>
    <%= link_to theme.logo.filename, theme.logo if theme.logo.attached? %>
  </p>

  <p>
    <strong>Maxwidth:</strong>
    <%= theme.maxwidth %>
  </p>

  <p>
    <strong>Custom Head:</strong>
    <%= theme.customhead %>
  </p>

  <p>
    <strong>Customcss:</strong>
    <%= theme.customcss %>
  </p>
-->
<div style="padding: 2em;">
  <%= link_to theme.name, edit_theme_path(theme) %>
  <br/>
  <div style="font-size: 4rem;">
    <span style="color: <%= theme.backgroundcolor %>">■</span><span style="color: <%= theme.headingcolor %>">■</span><span style="color: <%= theme.textcolor %>">■</span><span style="color: <%= theme.primarycolor %>">■</span><span style="color: <%= theme.secondarycolor %>">■</span><span style="color: <%= theme.tertiarycolor %>">■</span><span style="color: <%= theme.quaternarycolor %>">■</span> 
  </div>
  <% if theme.logo.attached? %>
  <img style="max-height: 200px; width: auto;" src="<%= url_for(theme.logo) %>"> 
  <% end %> 
</div>


</div>

app/views/themes/edit.html.erb
<h1>Editing theme</h1>

<%= render "form", theme: @theme %>

<br>

<div>
  <%= link_to "Show this theme", @theme %> |
  <%= link_to "Back to themes", themes_path %>
</div>

app/views/themes/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Themes</h1>

<div id="themes">
  <% @themes.each do |theme| %>
    <%= render theme %>
    <p>
      <%= link_to "Show this theme", theme %>
    </p>
  <% end %>
</div>

<%= link_to "New theme", new_theme_path %>

app/views/themes/new.html.erb
<h1>New theme</h1>

<%= render "form", theme: @theme %>

<br>

<div>
  <%= link_to "Back to themes", themes_path %>
</div>

app/views/themes/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @theme %>

<div>
  <%= link_to "Edit this theme", edit_theme_path(@theme) %> |
  <%= link_to "Back to themes", themes_path %>

  <%= button_to "Destroy this theme", @theme, method: :delete %>
</div>