config/routes.rb
Rails.application.routes.draw do
  resources :journalists
  resources :settings
  resources :themes
  resources :categories
  resources :stories
  devise_for :users
  
  get '/', to: 'home#index'
  get '/about', to: 'home#about'
  get '/contact', to: 'home#contact'
  root to: "home#index"

  get '/journalistdashboard', to: 'home#dashboard'
  get '/drafts', to: 'stories#drafts'
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"


  #this has to be last so user created categories don't override the application links
  get '/:name', to: 'categories#public'

end

app/controllers/home_controller.rb
require 'date'
class HomeController < ApplicationController
  before_action :authenticate_user!, only: [:dashboard]
  def index
  end

  def about
  end

  def contact
  end

  def dashboard
    @setting = Setting.last
    @themes = Theme.all
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/about.html.erb
<h1>Home#about</h1>
<p>Find me in app/views/home/about.html.erb</p>

app/views/home/contact.html.erb
<h1>Home#contact</h1>
<p>Find me in app/views/home/contact.html.erb</p>

app/views/home/dashboard.html.erb
<h1>Dashboard</h1>
<p style="padding: 3rem;">“The basis of our governments being the opinion of the people, the very first object should be to keep that right; and were it left to me to decide whether we should have a government without newspapers, or newspapers without a government, I should not hesitate a moment to prefer the latter.” – Thomas Jefferson</p>

<!-- IF USER IS EDITOR? -->
<h2>Settings | <%= link_to "Edit", edit_setting_path(@setting) %></h2>
<% if @setting.nil? %>
<%= link_to "New Settings", new_setting_path %>
<% else %>
<label>Name</label>
<blockquote><h1><%= @setting.newspapername %></h1></blockquote>
<label>Tagline</label>
<blockquote><h2><%= @setting.tagline %></h2></blockquote>
<br/>
<br/>
<label>Current Theme:</label>
<blockquote><h3><%= @setting.theme.name %></h3></blockquote>
<br/>
<br/>
<% end %>

<h2>Themes | <%= link_to "New", new_theme_path %></h2>
<% unless @themes.nil? %>
	<% @themes.each do |theme| %>
	<div style="padding: 2em;">
		<%= link_to theme.name, edit_theme_path(theme) %>
		<br/>
		<div style="font-size: 4rem;">
			<span style="color: <%= theme.backgroundcolor %>">■</span><span style="color: <%= theme.headingcolor %>">■</span><span style="color: <%= theme.textcolor %>">■</span><span style="color: <%= theme.primarycolor %>">■</span><span style="color: <%= theme.secondarycolor %>">■</span><span style="color: <%= theme.tertiarycolor %>">■</span><span style="color: <%= theme.quaternarycolor %>">■</span> 
		</div>
		<% if theme.logo.attached? %>
		<img style="max-height: 200px; width: auto;" src="<%= url_for(theme.logo) %>"> 
		<% end %>	
	</div>
	<% end %>
<% end %>
<br/>
<br/>
<h2>Categories | <%= link_to "New", new_category_path %></h2>
<div style="display: inline-flex;">
<% unless Category.nil? %>
  <% Category.all.each do |category| %>
	<a href="categories/<%= category.id %>/edit" style="text-decoration: none; border: none; border-bottom: 2px solid; border-color: <%= category.color %>; order: <%= category.order %>; padding: 2em;"><%= category.name.upcase + " & order: " + category.order.to_s %></a>
  <% end %>
<% end %>
</div>
<br/><br/>
<!-- END IF USER IS EDITOR? -->

<h2>Stories | <%= link_to "New", new_story_path %></h2>
<% unless Story.nil? %>
  <% Story.all.each do |story| %>
	<h5><%= unless story.publish? then "Draft: " end %><a href="stories/<%= story.slug %>"><%= story.title %></a> | <a href="stories/<%= story.slug %>/edit">EDIT</a></h5>
  <% end %>
<% end %>

app/views/home/index.html.erb
<h1 style="text-align: right;"><%= DateTime.now.strftime("%A, %B, %d, %Y %l:%M %P") %></h1>
<h2>
<% if Setting.last.nil? %>
All The News. All The Time.
<% else %>
<%= Setting.last.tagline %>
<% end %>
</h2>
[PUT IMAGE VIDEO OR AUDIO]