config/routes.rb
Rails.application.routes.draw do
  resources :journalists
  resources :settings
  resources :themes
  resources :categories
  resources :stories
  devise_for :users
  
  get '/', to: 'home#index'
  get '/about', to: 'home#about'
  get '/contact', to: 'home#contact'
  root to: "home#index"

  get '/journalistdashboard', to: 'home#dashboard'
  get '/drafts', to: 'stories#drafts'
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"


  #this has to be last so user created categories don't override the application links
  get '/:name', to: 'categories#public'

end

app/models/setting.rb
class Setting < ApplicationRecord
  belongs_to :theme
end

app/controllers/settings_controller.rb
class SettingsController < ApplicationController
  before_action :set_setting, only: %i[ show edit update destroy ]
  before_action :authenticate_user!
  before_action :only1setting, only: %i[ new ]
  before_action :only_editors

  def only_editors
    unless current_user.journalist.is_editor?
      flash[:alert] = 'You are not signed in as an authorized editor of this newspaper.'
      redirect_back(fallback_location: root_path)
    end
  end

  def only1setting
    unless Setting.last == nil
      flash[:alert] = 'You already have settings!'
      redirect_to '/journalistdashboard'
    end
  end

  # GET /settings or /settings.json
  def index
    @settings = Setting.all
  end

  # GET /settings/1 or /settings/1.json
  def show
  end

  # GET /settings/new
  def new
    @setting = Setting.new
  end

  # GET /settings/1/edit
  def edit
  end

  # POST /settings or /settings.json
  def create
    @setting = Setting.new(setting_params)

    respond_to do |format|
      if @setting.save
        format.html { redirect_to setting_url(@setting), notice: "Setting was successfully created." }
        format.json { render :show, status: :created, location: @setting }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @setting.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /settings/1 or /settings/1.json
  def update
    respond_to do |format|
      if @setting.update(setting_params)
        format.html { redirect_to setting_url(@setting), notice: "Setting was successfully updated." }
        format.json { render :show, status: :ok, location: @setting }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @setting.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /settings/1 or /settings/1.json
  def destroy
    @setting.destroy!

    respond_to do |format|
      format.html { redirect_to settings_url, notice: "Setting was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_setting
      @setting = Setting.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def setting_params
      params.require(:setting).permit(:newspapername, :tagline, :theme_id)
    end
end

app/helpers/settings_helper.rb
module SettingsHelper
end

app/views/settings/_form.html.erb
<%= form_with(model: setting) do |form| %>
  <% if setting.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(setting.errors.count, "error") %> prohibited this setting from being saved:</h2>

      <ul>
        <% setting.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :newspapername, "Newspaper Name", style: "display: block" %>
    <%= form.text_field :newspapername %>
  </div>

  <div class="field">
    <%= form.label :tagline, style: "display: block" %>
    <%= form.text_field :tagline %>
  </div>

  <div class="field">
    <%= form.label :theme_id, style: "display: block" %>
    <%= collection_select(:setting, :theme_id, Theme.all, :id, :name, prompt: true ) %>
  </div>

  <br><br>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/settings/_setting.html.erb
<div id="<%= dom_id setting %>">
  <p>
    <strong>Newspapername:</strong>
    <%= setting.newspapername %>
  </p>

  <p>
    <strong>Tagline:</strong>
    <%= setting.tagline %>
  </p>

  <p>
    <strong>Theme:</strong>
    <%= setting.theme_id %>
  </p>

</div>

app/views/settings/edit.html.erb
<h1>Edit Settings</h1>

<%= render "form", setting: @setting %>

<br><br>

<div>
  <%= link_to "Back To Dashboard", "/journalistdashboard" %>
</div>

app/views/settings/index.html.erb
<h1>Settings</h1>

<div id="settings">
  <% @settings.each do |setting| %>
    <%= render setting %>
    <p>
      <%= link_to "Goto this Setting", setting %>
    </p>
  <% end %>
</div>

<%= link_to "New setting", new_setting_path %>

app/views/settings/new.html.erb
<h1>New setting</h1>

<%= render "form", setting: @setting %>

<br>

<div>
  <%= link_to "Settings", settings_path %>
</div>

app/views/settings/show.html.erb
<%= render @setting %>

<div>
  <%= link_to "Edit this setting", edit_setting_path(@setting) %> |
  <%= link_to "Back to settings", settings_path %>
</div>

<br><br>

<div>
<%= button_to "Delete this setting", @setting, method: :delete, class: "deletebutton" %>
</div>